[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "learn-esp32"
authors = [{name = "lonelybinary", email = "office@lonelybinary.com"}]
dynamic = ["version", "description"]
